#templates for emails (html style) for MRIQC weekly report

# Sarah Hennessy, shennessy@arizona.edu
# last edit Jan 4, 2026


from __future__ import annotations
from pathlib import Path
from datetime import date

def build_mriqc_email_html(
    *,
    seven_days_ago: str,
    today: str,
    output_directory: Path,
    ntargets: int,
    nbaseline: int,
    nscan2: int,
    counts: dict[str, int],
) -> str:
    # counts expects keys: baseline_t1, baseline_rest, baseline_ta, scan2_t1, scan2_rest, scan2_ta
    return f"""
    <html>
      <body style="font-family: Arial, sans-serif; font-size: 14px; color: #111;">
        <h2 style="margin-bottom: 6px;">MRIQC Mini-Report</h2>

        <div style="margin-bottom: 14px;">
          <b>Date window processed:</b> {seven_days_ago} – {today}<br/>
          <span style="color:#555;">
            Note: This is an automated report generated by <code>master_mriqc.py</code>, reflecting scans
            <i>processed</i> during this time period (data collection may have happened earlier).
          </span><br/><br/>
          <b>Outputs saved to:</b> <code>{output_directory}</code><br/>
          <b>Subjects processed this week:</b> {ntargets} total
          (<b>{nbaseline}</b> baseline; <b>{nscan2}</b> scan 2)
        </div>

        <hr style="border: none; border-top: 1px solid #ddd; margin: 18px 0;" />

        <h3 style="margin: 0 0 8px 0;">Baseline</h3>

        <div style="margin-bottom: 18px;">
          <div style="margin: 12px 0;">
            <b>T1</b> <span style="color:#666;">(n = {counts.get("baseline_t1", 0)})</span><br/>
            <img src="cid:baseline_t1" style="max-width: 900px; width: 100%; height: auto; border: 1px solid #eee; border-radius: 6px;" />
          </div>

          <div style="margin: 12px 0;">
            <b>Resting State (BOLD)</b> <span style="color:#666;">(n = {counts.get("baseline_rest", 0)})</span><br/>
            <img src="cid:baseline_rest" style="max-width: 900px; width: 100%; height: auto; border: 1px solid #eee; border-radius: 6px;" />
          </div>

          <div style="margin: 12px 0;">
            <b>Think Aloud (BOLD)</b> <span style="color:#666;">(n = {counts.get("baseline_ta", 0)})</span><br/>
            <img src="cid:baseline_ta" style="max-width: 900px; width: 100%; height: auto; border: 1px solid #eee; border-radius: 6px;" />
          </div>
        </div>

        <h3 style="margin: 0 0 8px 0;">Scan 2</h3>

        <div style="margin-bottom: 18px;">
          <div style="margin: 12px 0;">
            <b>T1</b> <span style="color:#666;">(n = {counts.get("scan2_t1", 0)})</span><br/>
            <img src="cid:scan2_t1" style="max-width: 900px; width: 100%; height: auto; border: 1px solid #eee; border-radius: 6px;" />
          </div>

          <div style="margin: 12px 0;">
            <b>Resting State (BOLD)</b> <span style="color:#666;">(n = {counts.get("scan2_rest", 0)})</span><br/>
            <img src="cid:scan2_rest" style="max-width: 900px; width: 100%; height: auto; border: 1px solid #eee; border-radius: 6px;" />
          </div>

          <div style="margin: 12px 0;">
            <b>Think Aloud (BOLD)</b> <span style="color:#666;">(n = {counts.get("scan2_ta", 0)})</span><br/>
            <img src="cid:scan2_ta" style="max-width: 900px; width: 100%; height: auto; border: 1px solid #eee; border-radius: 6px;" />
          </div>
        </div>

        <hr style="border: none; border-top: 1px solid #ddd; margin: 18px 0;" />

        <div style="color:#666; font-size: 12px;">
          If a panel is missing or has n = 0, no scans of that type were processed during this window
          or the filename filter did not match.
        </div>
      </body>
    </html>
    """
