#templates for emails (html style) for MRIQC weekly report

# Sarah Hennessy, shennessy@arizona.edu
# last edit Jan 6, 2026


from __future__ import annotations
from pathlib import Path

def _panel_html(label: str, n: int, cid: str) -> str:
    return f"""
      <div style="margin: 12px 0;">
        <b>{label}</b> <span style="color:#666;">(n = {n})</span><br/>
        <img src="cid:{cid}"
             style="max-width: 900px; width: 100%; height: auto;
                    border: 1px solid #eee; border-radius: 6px;" />
      </div>
    """

def build_mriqc_email_html(
    *,
    seven_days_ago: str,
    today: str,
    output_directory: Path,
    ntargets: int,
    nbaseline: int,
    nscan2: int,
    counts: dict[str, int],
    available_cids: set[str],
) -> str:
    # Define panels 
    baseline_panels = [
        ("T1", "baseline_t1", counts.get("baseline_t1", 0)),
        ("Resting State (BOLD)", "baseline_rest", counts.get("baseline_rest", 0)),
        ("Think Aloud (BOLD)", "baseline_ta", counts.get("baseline_ta", 0)),
    ]
    scan2_panels = [
        ("T1", "scan2_t1", counts.get("scan2_t1", 0)),
        ("Resting State (BOLD)", "scan2_rest", counts.get("scan2_rest", 0)),
        ("Think Aloud (BOLD)", "scan2_ta", counts.get("scan2_ta", 0)),
    ]

    # Keep only panels whose images were actually generated/attached
    baseline_panels = [p for p in baseline_panels if p[1] in available_cids]
    scan2_panels = [p for p in scan2_panels if p[1] in available_cids]

    baseline_html = "\n".join(_panel_html(label, n, cid) for label, cid, n in baseline_panels)
    scan2_html = "\n".join(_panel_html(label, n, cid) for label, cid, n in scan2_panels)

    # Only include section headers if we have at least one panel
    baseline_section = ""
    if baseline_panels:
        baseline_section = f"""
        <h3 style="margin: 0 0 8px 0;">Baseline</h3>
        <div style="margin-bottom: 18px;">
          {baseline_html}
        </div>
        """

    scan2_section = ""
    if scan2_panels:
        scan2_section = f"""
        <h3 style="margin: 0 0 8px 0;">Scan 2</h3>
        <div style="margin-bottom: 18px;">
          {scan2_html}
        </div>
        """

    if not baseline_panels and not scan2_panels:
        # Fallback: no figures available at all
        figures_note = """
        <div style="margin: 12px 0; color:#a00;">
          No figures were generated for this window (no matching scans processed, or missing TSV inputs).
        </div>
        """
    else:
        figures_note = ""

    key_html = """
    <ul style="margin: 8px 0 0 18px; padding: 0; color:#666; font-size: 12px;">
      <li><b>cjv</b>: coefficient of joint variation (GM/WM). Higher often indicates motion/INU artifacts; lower is better.</li>
      <li><b>cnr</b>: contrast-to-noise ratio; higher is better.</li>
      <li><b>qi_2</b>: Mortamet’s quality index 2; lower is better.</li>
      <li><b>fd_mean</b>: mean framewise displacement; lower is better.</li>
      <li><b>snr</b>: signal-to-noise ratio (bold: often tSNR); higher is better.</li>
      <li><b>dvars_nstd</b>: standardized DVARS (rate of whole-brain BOLD change); lower is better.</li>
    </ul>
    """

    return f"""
    <html>
      <body style="font-family: Arial, sans-serif; font-size: 14px; color: #111;">
        <h2 style="margin-bottom: 6px;">MRIQC Mini-Report</h2>

        <div style="margin-bottom: 14px;">
          <b>Date window processed:</b> {seven_days_ago} – {today}<br/>
          <span style="color:#555;">
            Note: This is an automated report generated by <code>weekly_mriqc.py</code>, reflecting scans
            <i>processed</i> during this time period (data collection may have happened earlier).
          </span><br/><br/>
          <b>Outputs saved to:</b> <code>{output_directory}</code><br/>
          <b>Subjects processed this week:</b> {ntargets} total
          (<b>{nbaseline}</b> baseline; <b>{nscan2}</b> scan 2)
        </div>

        <hr style="border: none; border-top: 1px solid #ddd; margin: 18px 0;" />

        {figures_note}

        {baseline_section}

        {scan2_section}

        <hr style="border: none; border-top: 1px solid #ddd; margin: 18px 0;" />
        <div style="color:#666; font-size: 12px;">
        <b>Key:</b>
        {key_html}
        <div style="margin-top: 8px;">
          If a panel is missing, no scans of that type were processed during this window
          or the filename filter did not match.
        </div>
      </div>
      </body>
    </html>
    """

